### DISCUSSION TITLE
Docker-in-Docker works for Gitlab CI

### DISCUSSION THREAD

**Discussion by tomsvetna** [wKich/creevey#191] [Show and tell]
Hi, first of all thank you for a great tool. Second I just wanted to share that I was able to run creevey in Gitlab CI very easily with this setup:

```
test:
    stage: test
    services:
        - docker:18.09.7-dind
    variables:
        DOCKER_DRIVER: overlay
        DOCKER_HOST: tcp://localhost:2375
    script:
        - yarn storybook &
        - yarn creevey
    allow_failure: true
    artifacts:
        paths:
            - .creevey/report
        expire_in: 10 days
        when: always
```

Maybe it could be helpful for someone looking for CI solution :)
